
version: '3'

services:
  pttracker:
    build: .
    container_name: pttracker
    volumes:
      - ./PtTracker.json:/app/linux/PtTracker/PtTracker.json
    restart: always
    ports:
      - "3000:3000"
